---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev-korner
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aputra/myapp-195:v2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests: # This is required for hpa
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: dev-korner
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: myapp